apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: demo
    environment: stg
    name: demo
  name: demo
---
apiVersion: v1
data:
  ENVIRONMENT: stg
kind: ConfigMap
metadata:
  labels:
    app: demo
    environment: stg
  name: stg-demo-config
  namespace: demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
    environment: stg
  name: stg-demo-loadbalancer-svc
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: demo
    environment: stg
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    environment: stg
  name: stg-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      environment: stg
  template:
    metadata:
      labels:
        app: demo
        environment: stg
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: stg-demo-config
          image: asia-east1-docker.pkg.dev/extended-spark-406211/k8s/demo:5c79f711c9c5101d18ec23956dd89816d82e43626976ba48b5da8efd4a32b7cd@sha256:1fbc15fc7c78ecef7d59da67e38eab6b3f64a31d492c3561c1142cf1c84e51f3
          name: demo
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 512Mi
