apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: demo
    environment: prd
    name: demo
  name: demo
---
apiVersion: v1
data:
  ENVIRONMENT: prod
kind: ConfigMap
metadata:
  labels:
    app: demo
    environment: prd
  name: prd-demo-config
  namespace: demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
    environment: prd
  name: prd-demo-loadbalancer-svc
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: demo
    environment: prd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    environment: prd
  name: prd-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      environment: prd
  template:
    metadata:
      labels:
        app: demo
        environment: prd
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: prd-demo-config
          image: asia-east1-docker.pkg.dev/extended-spark-406211/k8s/demo:d508f54a93207789033ba7b153d2ea15cd613aeba605a61b69a385bb16d0bcec@sha256:4e1fdf7f0c130bffbbb300bf8bafdcb199ab69435846462965389755f9fe17e7
          name: demo
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 512Mi
